server: 
  port: 8081
  servlet:
    context-path: /jwt-resource-server


spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/test
          jwk-set-uri: http://localhost:8083/auth/realms/test/protocol/openid-connect/certs